# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8094440f677f3d7418afdee193c5893a8ba215bf736a06d6d53bb7ef047941c2c4f2107d3a305035ab6d977c3ea938373fb759fbceea433550bb0bdee2809f92

test:
  secret_key_base: 5460cb529c6633e5ee2e715e3ef27cc0c85085b65c1014b2e12f0f590c3807d14e4293097816918f9f4e94981f5f787ed505010f9fc229d4121a0b569a472ecf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
